TrajectoryPlannerROS:
  max_vel_x: 0.45
  min_vel_x: 0.1
  max_rotational_vel: 1.0
  min_in_place_rotational_vel: 0.4

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  yaw_goal_tolerance: 0.20
  xy_goal_tolerance: 0.05
  latch_xy_goal_tolerance: true

  holonomic_robot: true
  meter_scoring: true
