obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.24, 0.19], [0.24, -0.19], [-0.24, -0.19], [-0.24, 0.19]] 
inflation_radius: 0.55
transform_tolerance : 0.5



point_cloud_sensor: {sensor_frame: sonar_frame, data_type: PointCloud2, topic: /pioneer/sonar, marking: true, clearing: true}
